apiVersion: v1
kind: Namespace
metadata:
  name: itemns
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: items.itemresource.net
spec:
  group: itemresource.net
  names:
    kind: Item
    shortNames:
    - item
    plural: items
    singular: item
  scope: Namespaced  
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              detail:
                type: string
            required: ["detail"]
        required: ["spec"]
